### ISSUE TITLE
Adicionar data de encerramento de C4P

### ISSUE THREAD

**Issue by joaocunha** [alinebastos/call-for-papers#28]
Hey :)

Sugiro usarmos duas datas:

```
Encerramento do C4P: 15 de junho de 2018
Data do evento: 15 de agosto de 2018
```

O que acham?

**Comment by alinebastos** [comment]
Eu acho uma ótima ideia, senão a gente acaba se perdendo até em quando tirar o evento do repositorio :)

**Comment by joaocunha** [comment]
Ok, vou adicionar nas próximas submissões, e vamos alterando os antigos :)
